name: Image CI

on:
  workflow_dispatch:
  push:
    paths: [ "/backend/**" ]
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
jobs:
  build-and-push:
    name: Build Image and Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secret.oidc_role_arn }}
    
    - name: AWS Authentication
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build the Backend Image
      run: |
        docker build --build-arg APP_ENV=prod -t "${{ secret.ECR_REGISTRY }}/${{ secret.ECR_REPOSITORY }}:${{ secret.IMAGE_TAG }}" ./backend
        docker push "${{ secret.ECR_REGISTRY }}/${{ secret.ECR_REPOSITORY }}:${{ secret.IMAGE_TAG }}"

    
